### ISSUE TITLE
Text overflows on market card

### ISSUE THREAD

**Issue by lsaether** [zeitgeistpm/ui#501]
![image](https://user-images.githubusercontent.com/25539605/207896556-b39ba218-5e73-4a41-b5dd-23966c5d49ca.png)

![image](https://user-images.githubusercontent.com/25539605/207896793-20a3cb98-fee2-4b16-8718-49adae6f67bd.png)

**Comment by TvrtkoM** [comment]
this should be fixed in the responsive grid PR #499

**Comment by lsaether** [comment]
#499 doesn't solve it, the problem still exists even on that PR 
<img width="741" alt="image" src="https://user-images.githubusercontent.com/25539605/208174658-3e7dc722-dc76-4476-802f-7b8a254af85a.png">

**Comment by robhyrk** [comment]
resolved in #499
